local function BuildArmorPanel(p)
    p:ClearControls()
    p:Help("Advanced Damage System - Armor")

    p:Help("System Toggles")
    p:CheckBox("Enable NPC armor system","ads_enabled_npc")
    p:CheckBox("Enable Player armor system","ads_enabled_ply")
    p:CheckBox("Engine hitgroup compensation (limb/head HP)","ads_engine_hitgroup_compensation")

    p:Help("Global Armor Defaults (fallback when no override)")
    p:NumSlider("NPC Min Armor","ads_min_arm",0,100,0)
    p:NumSlider("NPC Max Armor","ads_max_arm",0,100,0)
    p:NumSlider("Player Spawn Armor","ads_ply_arm",0,100,0)
    p:NumSlider("Min Reduction %","ads_red_min",0,100,0)
    p:NumSlider("Max Reduction %","ads_red_max",0,100,0)

    p:Help("Zonal Armor Effectiveness")
    p:NumSlider("Helmet Effectiveness","ads_helmet_mult",0,1,2)
    p:NumSlider("Blast Effectiveness","ads_blast_mult",0,1,2)
    p:NumSlider("Crush Effectiveness","ads_crush_mult",0,1,2)

    p:Help("Global Damage Multipliers (override per classname via toolgun)")
    p:NumSlider("Head damage mult","ads_limb_mult_head",0,5,2)
    p:NumSlider("Chest damage mult","ads_limb_mult_chest",0,5,2)
    p:NumSlider("Arm damage mult","ads_limb_mult_arm",0,5,2)
    p:NumSlider("Leg damage mult","ads_limb_mult_leg",0,5,2)

    p:Help("Detection")
    p:CheckBox("Enable VJ auto-detect","ads_vj_autodetect")

    p:Help("Effects")
    p:CheckBox("Enable Armor Hit Sound (metallic clang, hard plates)","ads_sound_enabled")
    p:CheckBox("Enable Gunshot-Blocked Sound","ads_gunshotblocked_enabled")
    p:CheckBox("Enable Headshot Sound","ads_headshot_sound_enabled")
    p:CheckBox("Block FX: suppress blood when armor blocks","ads_block_noblood_enabled")
    p:CheckBox("Block FX: metal spark on block","ads_block_spark_enabled")
    p:CheckBox("Block FX: metal impact decal on block","ads_block_decal_enabled")

    p:Help("Debug")
    p:CheckBox("Enable Debug Prints","ads_debug")

    p:Help("Reset")
    p:Button("Reset Armor Settings to Default").DoClick = function()
        Derma_Query("Reset Armor Settings to defaults?","ADS","Yes",function()
            RunConsoleCommand("ads_enabled_npc","1")
            RunConsoleCommand("ads_enabled_ply","1")
            RunConsoleCommand("ads_engine_hitgroup_compensation","1")
            RunConsoleCommand("ads_min_arm","0")
            RunConsoleCommand("ads_max_arm","100")
            RunConsoleCommand("ads_ply_arm","100")
            RunConsoleCommand("ads_red_min","15")
            RunConsoleCommand("ads_red_max","80")
            RunConsoleCommand("ads_helmet_mult","0.5")
            RunConsoleCommand("ads_blast_mult","0.5")
            RunConsoleCommand("ads_crush_mult","0.5")
            RunConsoleCommand("ads_limb_mult_head","1.0")
            RunConsoleCommand("ads_limb_mult_chest","1.0")
            RunConsoleCommand("ads_limb_mult_arm","1.0")
            RunConsoleCommand("ads_limb_mult_leg","1.0")
            RunConsoleCommand("ads_vj_autodetect","1")
            RunConsoleCommand("ads_sound_enabled","1")
            RunConsoleCommand("ads_gunshotblocked_enabled","1")
            RunConsoleCommand("ads_headshot_sound_enabled","1")
            RunConsoleCommand("ads_block_noblood_enabled","1")
            RunConsoleCommand("ads_block_spark_enabled","1")
            RunConsoleCommand("ads_block_decal_enabled","1")
            RunConsoleCommand("ads_debug","0")
        end,"No")
    end
end

local function BuildLimbsPanel(p)
    p:ClearControls()
    p:Help("Advanced Damage System - Limb HP")

    p:Help("System Toggle")
    p:CheckBox("Enable Limb HP System","ads_limbs_enabled")

    p:Help("HP Pool Fractions (per limb, fraction of NPC max HP)")
    p:NumSlider("Head HP fraction","ads_limb_head_frac",0,2,2)
    p:NumSlider("Arms HP fraction (per arm)","ads_limb_arms_frac",0,2,2)
    p:NumSlider("Legs HP fraction (per leg)","ads_limb_legs_frac",0,2,2)

    p:Help("Damage Transfer (fraction of damage that drains the pool)")
    p:NumSlider("Head damage transfer","ads_limb_damage_transfer_head",0,3,2)
    p:NumSlider("Arms damage transfer","ads_limb_damage_transfer_arms",0,3,2)
    p:NumSlider("Legs damage transfer","ads_limb_damage_transfer_legs",0,3,2)

    p:Help("Debuff Intensity")
    p:NumSlider("Max accuracy penalty per arm","ads_limb_accuracy_max_penalty_per_arm",0,5,2)
    p:NumSlider("Max accuracy penalty from head","ads_limb_accuracy_max_penalty_head",0,5,2)
    p:NumSlider("Min speed mult per leg","ads_limb_min_speed_mult_per_leg",0,1,2)

    p:Help("Head Stun Durations")
    p:NumSlider("Head stun 50% duration (s)","ads_limb_head_stun_50_duration",0,5,1)
    p:NumSlider("Head stun 25% duration (s)","ads_limb_head_stun_25_duration",0,10,1)

    p:Help("Reset")
    p:Button("Reset Limb HP Settings to Default").DoClick = function()
        Derma_Query("Reset Limb HP Settings to defaults?","ADS","Yes",function()
            RunConsoleCommand("ads_limbs_enabled","1")
            RunConsoleCommand("ads_limb_head_frac","0.5")
            RunConsoleCommand("ads_limb_arms_frac","0.5")
            RunConsoleCommand("ads_limb_legs_frac","0.5")
            RunConsoleCommand("ads_limb_damage_transfer_head","1.5")
            RunConsoleCommand("ads_limb_damage_transfer_arms","0.7")
            RunConsoleCommand("ads_limb_damage_transfer_legs","0.7")
            RunConsoleCommand("ads_limb_accuracy_max_penalty_per_arm","1.0")
            RunConsoleCommand("ads_limb_accuracy_max_penalty_head","0.5")
            RunConsoleCommand("ads_limb_min_speed_mult_per_leg","0.5")
            RunConsoleCommand("ads_limb_head_stun_50_duration","1.0")
            RunConsoleCommand("ads_limb_head_stun_25_duration","2.5")
        end,"No")
    end
end

local function BuildScavengerPanel(p)
    p:ClearControls()
    p:Help("Advanced Damage System - Scavenger")

    p:Help("System Toggle")
    p:CheckBox("Enable Scavenger","ads_scavenger_enabled")

    p:Help("Drop Lifetime and Cooldowns")
    p:NumSlider("Drop lifetime (seconds)","ads_scavenger_drop_lifetime",0,600,0)
    p:NumSlider("Post-drop cooldown (seconds)","ads_scavenger_post_drop_cooldown",0,60,0)
    p:NumSlider("Drop ownership time (seconds)","ads_scavenger_drop_ownership_time",0,300,0)

    p:Help("Detection")
    p:NumSlider("Search radius","ads_scavenger_search_radius",100,3000,0)
    p:NumSlider("Pickup distance","ads_scavenger_pickup_distance",10,200,0)
    p:NumSlider("Think interval (seconds)","ads_scavenger_think_interval",0.1,5,1)

    p:Help("Behavior Toggles")
    p:CheckBox("Allow combat interrupt for better weapons","ads_scavenger_interrupt_combat")
    p:CheckBox("Allow world weapons (map-spawned)","ads_scavenger_allow_world_weapons")
    p:CheckBox("Force all NPCs to scavenge (ignore detection)","ads_scavenger_force_all_npcs")

    p:Help("Retrieve Own Weapon Mode")
    p:Help("Armed NPCs never swap weapons. A disarmed NPC first tries to recover its own dropped weapon; if it fails, it falls back to normal scavenging. Timeout counts from the moment of the drop.")
    p:CheckBox("Retrieve own weapon (no upgrades)","ads_scavenger_retrieve_own")
    p:NumSlider("Retrieve delay (seconds)","ads_scavenger_retrieve_delay",0,10,1)
    p:NumSlider("Retrieve timeout (seconds)","ads_scavenger_retrieve_timeout",5,120,0)

    p:Help("Movement Mode")
    local modeCombo = vgui.Create("DComboBox", p)
    modeCombo:SetTall(22)
    local currentMode = GetConVar("ads_scavenger_movement_mode") and GetConVar("ads_scavenger_movement_mode"):GetString() or "run"
    modeCombo:AddChoice("Run", "run", currentMode == "run")
    modeCombo:AddChoice("Walk", "walk", currentMode == "walk")
    modeCombo.OnSelect = function(_, _, _, data)
        RunConsoleCommand("ads_scavenger_movement_mode", data)
    end
    p:AddItem(modeCombo)

    p:Help("Debug")
    p:CheckBox("Scavenger debug prints","ads_scavenger_debug")

    p:Help("Reset")
    p:Button("Reset Scavenger Settings to Default").DoClick = function()
        Derma_Query("Reset Scavenger Settings to defaults?","ADS","Yes",function()
            RunConsoleCommand("ads_scavenger_enabled","1")
            RunConsoleCommand("ads_scavenger_drop_lifetime","60")
            RunConsoleCommand("ads_scavenger_post_drop_cooldown","8")
            RunConsoleCommand("ads_scavenger_drop_ownership_time","30")
            RunConsoleCommand("ads_scavenger_search_radius","800")
            RunConsoleCommand("ads_scavenger_pickup_distance","40")
            RunConsoleCommand("ads_scavenger_think_interval","0.5")
            RunConsoleCommand("ads_scavenger_interrupt_combat","0")
            RunConsoleCommand("ads_scavenger_allow_world_weapons","0")
            RunConsoleCommand("ads_scavenger_force_all_npcs","0")
            RunConsoleCommand("ads_scavenger_retrieve_own","0")
            RunConsoleCommand("ads_scavenger_retrieve_delay","2")
            RunConsoleCommand("ads_scavenger_retrieve_timeout","20")
            RunConsoleCommand("ads_scavenger_movement_mode","run")
            RunConsoleCommand("ads_scavenger_debug","0")
        end,"No")
    end
end

local function BuildShieldPanel(p)
    p:ClearControls()
    p:Help("Advanced Damage System - Energy Shields")

    p:Help("System Toggle")
    p:CheckBox("Enable Energy Shield system","ads_shield_enabled")

    p:Help("Global Shield Tuning (per-NPC setup lives in the ADS Configuration browser, Energy Shield tab)")
    p:NumSlider("Shield damage mult","ads_shield_damage_mult",0,10,2)
    p:NumSlider("Plasma drain mult","ads_shield_plasma_mult",1,10,2)
    p:NumSlider("EMP recharge lockout (s)","ads_shield_emp_lockout",0,60,1)
    p:NumSlider("Recharge think interval (s)","ads_shield_think_interval",0.05,1,2)

    p:Help("Effects")
    p:CheckBox("Shield sounds (hits / collapse / charge)","ads_shield_sounds")
    p:CheckBox("Shield bubble (client)","ads_shield_fx_bubble")
    p:CheckBox("Shield particles (client)","ads_shield_fx_particles")

    p:Help("Weapon plasma/EMP flags live in the Weapons tab of the browser (hand-curated).")

    p:Help("Reset")
    p:Button("Reset Energy Shield Settings to Default").DoClick = function()
        Derma_Query("Reset Energy Shield Settings to defaults?","ADS","Yes",function()
            RunConsoleCommand("ads_shield_enabled","1")
            RunConsoleCommand("ads_shield_damage_mult","1.0")
            RunConsoleCommand("ads_shield_plasma_mult","2.0")
            RunConsoleCommand("ads_shield_emp_lockout","8.0")
            RunConsoleCommand("ads_shield_think_interval","0.1")
            RunConsoleCommand("ads_shield_sounds","1")
            RunConsoleCommand("ads_shield_fx_bubble","1")
            RunConsoleCommand("ads_shield_fx_particles","1")
        end,"No")
    end
end

hook.Add("PopulateToolMenu","ADS_RegisterMenu",function()
    spawnmenu.AddToolMenuOption("Options","Advanced Damage System","ADS_Armor",     "Armor Settings",         "","",BuildArmorPanel)
    spawnmenu.AddToolMenuOption("Options","Advanced Damage System","ADS_Limbs",     "Limb HP Settings",       "","",BuildLimbsPanel)
    spawnmenu.AddToolMenuOption("Options","Advanced Damage System","ADS_Shield",    "Energy Shield Settings", "","",BuildShieldPanel)
    spawnmenu.AddToolMenuOption("Options","Advanced Damage System","ADS_Scavenger", "Scavenger Settings",     "","",BuildScavengerPanel)
end)
